name: MoneyPlugin
main: me.mister.money.MoneyPlugin
version: 1.0
api-version: 1.21
author: Mister

commands:
  money:
    description: Voir votre argent
    usage: /money
  pay:
    description: Payer un joueur
    usage: /pay <joueur> <montant>
  bank:
    description: Banque du joueur
    usage: /bank
  moneyadmin:
    description: Commandes admin d'argent
    usage: /moneyadmin <set|add|remove|log> ...
  moneyhelp:
    description: Aide du plugin Money
    usage: /moneyhelp
